/* 
 * File:   MCAL_INTERRUPT_gen_cfg.h
 * Author: Nadine
 *
 * Created on November 20, 2023, 7:45 PM
 */

#ifndef MCAL_INTERRUPT_GEN_CFG_H
#define	MCAL_INTERRUPT_GEN_CFG_H

#define INT_FEATURE_ENABLE 1U

#define INT_PRIORITY_Levels_Enable          INT_FEATURE_ENABLE

#define EXTERNAL_INT_INTX_Enable            INT_FEATURE_ENABLE
#define EXTERNAL_INT_OnChange_Enable        INT_FEATURE_ENABLE

#define ADC_INT_FEATURE_ENABLE              INT_FEATURE_ENABLE

#define TMR0_INT_FEATURE_ENABLE             INT_FEATURE_ENABLE
#define TMR1_INT_FEATURE_ENABLE             INT_FEATURE_ENABLE
#define TMR2_INT_FEATURE_ENABLE             INT_FEATURE_ENABLE
#define TMR3_INT_FEATURE_ENABLE             INT_FEATURE_ENABLE

#define EUSART_TX_INT_FEATURE_ENABLE        INT_FEATURE_ENABLE
#define EUSART_RX_INT_FEATURE_ENABLE        INT_FEATURE_ENABLE

#define MSSP_I2C_INT_FEATURE_ENABLE         INT_FEATURE_ENABLE

#define CCP1_INT_FEATURE_ENABLE       INT_FEATURE_ENABLE
#define CCP2_INT_FEATURE_ENABLE       INT_FEATURE_ENABLE


#endif	/* MCAL_INTERRUPT_GEN_CFG_H */

